### ISSUE TITLE
Doctrine Embeddable Support

### ISSUE THREAD

**Issue by bobdercole** [K-Phoen/rulerz#26]
Hello,

First off, thank you for this awesome library! I am attempting to utilize RulerZ with Doctrine. I have a basic working implementation thanks to the [cookbook](https://github.com/K-Phoen/rulerz/blob/master/doc/cookbooks/doctrine_orm.md). However, I am facing an issue with [Doctrine Embeddables](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/tutorials/embeddables.html).

Here is a snippet of my entity map file:

``` yaml
Website:
    type: entity
    table: websites
    embedded:
        domain_name:
            class: DomainName
```

Here is a snippet of my embeddable map file:

``` yaml
DomainName:
  type: embeddable
  fields:
    value:
        type: string
        nullable: false
        length: 255
        options:
            fixed: false
        column: url
```

Here is a snippet of my RulerZ specification file:

``` php
public function getRule()
{
    return 'domain_name.value = :domain_name';
}

public function getParameters()
{
    return [
        'domain_name' => $this->domain_name
    ];
}
```

According to the [Doctrine documentation](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/tutorials/embeddables.html#dql), the DQL should look like this:

``` sql
SELECT w FROM Website w WHERE w.domain_name.value = :domain_name
```

However, RulerZ is treating the embeddable as an association. The generated DQL looks like this:

``` sql
SELECT w FROM Website w INNER JOIN w.domain_name rulerz_domain_name WHERE rulerz_domain_name.value = :domain_name
```

What am I doing wrong?
