### ISSUE TITLE
Testing for null

### ISSUE THREAD

**Issue by xdimedrolx** [K-Phoen/rulerz#85]
Hello.
I want to check that a value **_is null_** or **_is not null_**. 
Now I got error: _Expected known function, got 'is'"_ 
How can I do it?

**Comment by Shandur** [comment]
@xdimedrolx Have you fixed the problem? I got the same.

**Comment by xdimedrolx** [comment]
@Shandur 
I use symfony. I add operator _is_:

```php 
<?php
namespace App\Infrastructure\Rulerz\Operator\DoctrineExecutor;
use function sprintf;
class Is
{
    public function __invoke($a, $b)
    {
        return sprintf('%s IS %s', $a, $b);
    }
}
```
in service config:

```yml
rulerz.operator.doctrine.is:
      class: App\Infrastructure\Rulerz\Operator\DoctrineExecutor\Is
      tags:
        - { name: rulerz.operator, inline: true, target: doctrine, operator: is }
```
